Feature/assignment 6
pranjhi-successive/js-training pull request #6
Opened 2023-10-10 07:26 UTC by pranjhi-successive

Assignment6

2023-10-12 11:22 UTC, pranjhi-successive commented
updated

2023-10-16 05:47 UTC, vks-successive requested changes

2023-10-16 05:47 UTC, vks-successive commented on Assignment_Day6/Question1.js
> +class bankAccount {
class name starts with capital letter

2023-10-16 05:47 UTC, vks-successive commented on Assignment_Day6/Question2.js
> +    getArea(){
as this function is in parent class, so no need to re-declare

2023-10-16 10:51 UTC, vks-successive approved these changes

2023-10-16 10:52 UTC, merged